services:
  kong:
    image: kong:${KONG_VERSION}
    environment:
      KONG_DATABASE: "off"
      KONG_DECLARATIVE_CONFIG: "/usr/local/kong/declarative/kong.yml"
      KONG_LOG_LEVEL: "info"
      KONG_PROXY_ACCESS_LOG: "/dev/stdout"
      KONG_ADMIN_ACCESS_LOG: "/dev/stdout"
      KONG_PROXY_ERROR_LOG: "/dev/stderr"
      KONG_ADMIN_ERROR_LOG: "/dev/stderr"
      KONG_ADMIN_LISTEN: "0.0.0.0:8001"
      KONG_PLUGINS: "bundled,${PLUGIN_NAME}"
      KONG_NGINX_HTTP_LUA_SHARED_DICT: "${PLUGIN_NAME} 1m"
    volumes:
      - plugin-development:/plugin-development
      - ./kong.yml:/usr/local/kong/declarative/kong.yml
    user: root
    entrypoint: /bin/sh
    ports:
      - "8000:8000"
      - "8443:8443"
      - "8001:8001"
      - "8444:8444"
    command: 
      - -c
      - |-
        ln -s /plugin-development /usr/local/share/lua/5.1/kong/plugins/${PLUGIN_NAME}
        /docker-entrypoint.sh kong docker-start

  httpbin:
    image: kennethreitz/httpbin

  prometheus:
    image: prom/prometheus
    ports:
      - "9090:9090"
    entrypoint: /bin/sh
    command: 
      - -c
      - |-
        cat <<EOD > /etc/prometheus/prometheus.yml
        global:
          scrape_interval: 15s

        scrape_configs:
          - job_name: 'prometheus'
            static_configs:
              - targets: ['localhost:9090']
          - job_name: 'kong'
            static_configs:
              - targets: ['kong:8001']
        EOD

        /bin/prometheus --config.file=/etc/prometheus/prometheus.yml --storage.tsdb.path=/prometheus

volumes:
  plugin-development:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ./kong/plugins/${PLUGIN_NAME}
